---
name: Discord Post Updater
author: Harry Reeder <harry@reeder.dev>
description: Update a post in Discord 
inputs:
  discord_token:
    description: Discord Bot Token for Authentication
    required: true
  post_file:
    description: Path to the file containing the raw post
    required: false
  post_xml:
    description: Path to the file containing the XML specification for the post
    required: false
  discord_channel:
    description: Discord Channel ID
    required: true
  discord_message:
    description: Existing message ID to update (must be owned by the bot user)
    required: false
  use_embed:
    description: Whether to use an embed (title extracted from top line heading in file) or a regular message. Defaults to regular.
    required: false
  embed_color:
    description: Decimal color for the embed if using an embed. Defaults to 0.
    required: false
runs:
  using: docker
  image: Dockerfile
branding:
  icon: edit
  color: purple
